"""The migrations and the models must not drift apart.

Postgres is built by ``alembic upgrade head`` and nothing else (app/database.py
refuses to serve a Postgres database that is not at head), so a column added to
a model without a matching revision does not fail here — it fails on the day
someone deploys, as a query error against a column that was never created.

These tests run entirely on throwaway SQLite files, so they need no Postgres
and no network.  What they check is dialect-independent: that the revisions,
replayed from nothing, produce exactly the schema the models describe.
"""
from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

BACKEND = Path(__file__).resolve().parent.parent
BASELINE = "fa843d18c61e"


def _config(db_path: Path) -> Config:
    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "alembic"))
    # Explicit override: never touch the database this test run is using.
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path.as_posix()}")
    return cfg


def test_upgrade_head_builds_every_table(tmp_path):
    db = tmp_path / "fresh.db"
    command.upgrade(_config(db), "head")

    tables = set(inspect(create_engine(f"sqlite:///{db.as_posix()}")).get_table_names())
    assert {"customs_job", "uploaded_document", "xml_artifact",
            "bms_artifact", "audit_event"} <= tables
    # Without this index every job listing is a full scan once ownership filters.
    engine = create_engine(f"sqlite:///{db.as_posix()}")
    indexes = {i["name"] for i in inspect(engine).get_indexes("customs_job")}
    assert "ix_customs_job_owner_key" in indexes


def test_migrations_match_the_models(tmp_path):
    """`alembic check` — the guard that actually earns its keep.

    Add a column to a model, forget the revision, and this fails with the diff
    it would have generated.
    """
    db = tmp_path / "check.db"
    cfg = _config(db)
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as diff:
        pytest.fail(
            f"The models and the migrations disagree: {diff}\n"
            f"A model changed without a revision. Generate one with:\n"
            f"    cd backend && alembic revision --autogenerate -m 'describe it'")


def test_downgrade_is_reversible(tmp_path):
    """Up, down, up again — a revision nobody can undo is a revision nobody
    can safely deploy."""
    db = tmp_path / "cycle.db"
    cfg = _config(db)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    engine = create_engine(f"sqlite:///{db.as_posix()}")
    assert "customs_job" not in set(inspect(engine).get_table_names())
    command.upgrade(cfg, "head")
    assert "customs_job" in set(inspect(create_engine(f"sqlite:///{db.as_posix()}")).get_table_names())


def test_baseline_is_still_the_root_revision():
    """app/database.py prints `alembic stamp fa843d18c61e` to whoever owns a
    pre-alembic database.  If the root revision is ever renumbered, that
    instruction starts pointing at nothing — and the person reading it has a
    database with real declarations in it."""
    from alembic.script import ScriptDirectory

    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "alembic"))
    roots = list(ScriptDirectory.from_config(cfg).get_bases())
    assert roots == [BASELINE], (
        f"the root revision is {roots}, but app/database.py tells operators to "
        f"stamp {BASELINE}")
